//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeriodTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PeriodTracker.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement date.
        /// </summary>
        internal static string ComplementButton {
            get {
                return ResourceManager.GetString("ComplementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        internal static string ComplementPageTitle {
            get {
                return ResourceManager.GetString("ComplementPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try out demo mode.
        /// </summary>
        internal static string DemoButtonText {
            get {
                return ResourceManager.GetString("DemoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can start demo mode using dummy data to try out different functionalities of the app.
        ///
        ///Demo mode will be left in case the app loses focus or is sent to background..
        /// </summary>
        internal static string DemoDescription {
            get {
                return ResourceManager.GetString("DemoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string DemoPageTitle {
            get {
                return ResourceManager.GetString("DemoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prediction.
        /// </summary>
        internal static string FuturePageTitle {
            get {
                return ResourceManager.GetString("FuturePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string HistoryDate {
            get {
                return ResourceManager.GetString("HistoryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Days.
        /// </summary>
        internal static string HistoryElapsedDays {
            get {
                return ResourceManager.GetString("HistoryElapsedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HistoryPageTitle {
            get {
                return ResourceManager.GetString("HistoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last occasion.
        /// </summary>
        internal static string LastDate {
            get {
                return ResourceManager.GetString("LastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next nominal occasion.
        /// </summary>
        internal static string NextNominalDate {
            get {
                return ResourceManager.GetString("NextNominalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next personalized occasion.
        /// </summary>
        internal static string NextPersonalizedDate {
            get {
                return ResourceManager.GetString("NextPersonalizedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining nominal days.
        /// </summary>
        internal static string RemainingNominalDays {
            get {
                return ResourceManager.GetString("RemainingNominalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining personalized days.
        /// </summary>
        internal static string RemainingPersonalizedDate {
            get {
                return ResourceManager.GetString("RemainingPersonalizedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save today.
        /// </summary>
        internal static string SaveToday {
            get {
                return ResourceManager.GetString("SaveToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string StatisticsPageTitle {
            get {
                return ResourceManager.GetString("StatisticsPageTitle", resourceCulture);
            }
        }
    }
}
